# Generated by Django 4.1.5 on 2023-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image",
        ),
        migrations.AddField(
            model_name="car",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
